config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  
  root to:'homes#top'
  get 'home/about' => 'homes#about'
  

  resources :books, only: [ :create, :edit, :update, :index, :show, :destroy] do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments,only: [:create,:destroy]
  end
  
  resources :users,only:[:index,:show,:edit,:update] do
    resource :relationships,only: [:create,:destroy]
    get 'followings' => 'relationships#followings', as:'followings'
    get 'followers' => 'relationships#followers', as:'followers'
  end
  
  get 'search' => "searches#search"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord


belongs_to :user
has_many :favorites,dependent: :destroy
has_many :book_comments,dependent: :destroy

def favorited_by?(user)
  favorites.where(user_id:user.id).exists?
end


  def self.looks(searches, words)
    if searches == "perfect_match"
      @book = Book.where("title LIKE ?","#{words}")
    elsif searches == "forward_match"
      @book = Book.where("title Like ?","#{words}%")
    elsif searches == "backward_match"
      @book = Book.where("title Like ?","%#{words}")
    else
      @book = Book.where("title LIKE ?","%#{words}%")
    end
  end

validates :title, presence: true
validates :body, presence: true, length: { maximum: 200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
belongs_to :user
belongs_to :book

validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

belongs_to :user
belongs_to :book

validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books,dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :book_comments,dependent: :destroy
  
  
  
  has_many :relationships, class_name: "Relationship",foreign_key: "follower_id",dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship",foreign_key: "followed_id",dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?","#{words}")
    elsif searches == "forward_match"
      @user = User.where("name Like ?","#{words}%")
    elsif searches == "backward_match"
      @user = User.where("name Like ?","%#{words}")
    else
      @user = User.where("name LIKE ?","%#{words}%")
    end
  end

  
  attachment :profile_image
  
validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
validates :introduction, length: { maximum: 50 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_inactive_sign_up_path_for(resource)
    user_path(resource)                   
  end
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
    render :index
 
  end

  def destroy
    @book = Book.find(params[:book_id])
  	book_comment = @book.book_comments.find(params[:id])
		book_comment.destroy
    render :index
  end
  
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
  
  
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end
  
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if  @book.save
      flash[:notice] = 'Book was successfully created.'      
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user= current_user
      render :index
    end
  end
  
  
  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.' 
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  

  def show
    @book = Book.find(params[:id])
    @book_list = Book.new
    @user_list = @book.user
    @book_comment = BookComment.new
  end
  
  
  

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
   @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save

  end
  
  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy

  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

def top
end

def about
end


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search],params[:word])
    else
      @books = Book.looks(params[:search],params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @book_list = Book.new
    @users = User.all
    @user_list = current_user
  end 
  
  
  
  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book_list = Book.new
  end
  
  
  def edit
   @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  

  
  
  private
  
  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comments.html.erb
      <table class="table">
        <p>コメント件数:<%= book.book_comments.count %></p>
        <% book.book_comments.each do |book_comment| %>
          <tr>  
            <td>
              <%= link_to user_path(book_comment.user.id) do %>
              <%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg",size: "40x40" %>
              <br>
              <%= book_comment.user.name %>
              <% end %>
            </td>
            <td><%= book_comment.comment %></td>
            <% if book_comment.user == current_user %>
            <td>
              <%= link_to "Destroy",book_book_comment_path(book_comment.book,book_comment),class:'btn btn-sm btn-danger',method: :delete, remote: true %>
            </td>
            <% else %>
              <td></td>
            <% end %>
          </tr>
        <% end %>
      </table>
      
      
      
        
        
        
        
        

app/views/book_comments/_new_comment.html.erb
<%= form_with(model:[book,book_comment]) do |f| %>
  <div class="form-group">
  <%= f.text_area :comment,class:"form-control"%>
  </div>
  <div class="form-group"><%= f.submit"送信"%></div>
<% end %>

app/views/book_comments/index.js.erb
$("#comments").html("<%= j(render 'book_comments/comments', { book: @book }) %>")
$("textarea").val('')

app/views/books/_list.html.erb
 <div class='col-md-3'>
    <h2>User info</h2>
    <table class='table'>
      <tr><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></tr>
      <tr>
        <th>name</th>
	      <th><%= user.name %></th>
      </tr>
      <tr>
	      <th>introduction</th>
	      <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follow</th>
        <th><%= link_to "#{user.followings.count}", user_followings_path(user.id) %></th>
      </tr>
      <tr>
        <th>follower</th>
        <th><%= link_to "#{user.followers.count}", user_followers_path(user.id) %></th>
      </tr>
    </table>
    
    
    
    
    <div>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), class:"btn btn-info", method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), class:"btn btn-info", method: :post %>
            <% end %>
          <% end %>
    </div>
    
    
    
    <br>
    
    <div class='row'>
        <%= link_to edit_user_path(user.id) ,class:"btn btn-outline-secondary btn-block fas fa-user-cog" do %>
        <% end %>
    </div>  



    <h2 class="mt-3">New book</h2>
    <%= form_with model:book, local:true do |f| %>

    
      <div class="form-group">
        <label for="book_name">Title</label>
        <%= f.text_field :title, autofocus: true, class:"form-control",id:"inputTitle"%>
      </div>
      
    
      <div class="form-group">
        <label for="book_body">Opinion</label>
        <%= f.text_area :body, autofocus: true, class:"form-control",id:"inputBody"%>
      </div>
      
      
    
 
    <div class="action">
      <%= f.submit 'Create Book',class:"btn btn-success"%>
    </div>
    <% end %>
    
  </div>
  
  
  
  

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h1>Editing Book</h1>

       <% if @book.errors.any? %>
         <div id="error_explanation">
           <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
           <ul>
             <% @book.errors.full_messages.each do |message| %>
             <li><%= message %></li>
             <% end %>
           </ul>
         </div>
       <% end %>
                
             
        <%= form_with model:@book, local:true do |f| %>
 
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, autofocus: true, class:"form-control",id:"inputTitle"%>
      </div>
 

    
      <div class="form-group">
        <label for="book_body">Opinion</label>
        <%= f.text_area :body, autofocus: true, class:"form-control",id:"inputbody"%>
      </div>
      
 
 
        <div class="form-group">
          <%= f.submit 'Update Book',class:"btn btn-success" %>
        </div>

        <% end %>

        <%= link_to "Show",book_path(@book.id) %> | 
        <%= link_to "Back",books_path %> 
      </div>
    </div>
  <div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  
  <div class="row"> 
    
    
    <div class='container px-5 px-sm-0'>
  <div class="row"> 
    
     <div class='col-md-3'>
    <h2>User info</h2>
    <table class='table'>
      <tr><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></tr>
      <tr>
        <th>name</th>
	      <th><%= @user.name %></th>
      </tr>
      <tr>
	      <th>introduction</th>
	      <th><%= @user.introduction %></th>
      </tr>
      <tr>
        <th>follow</th>
        <th><%= link_to "#{@user.followings.count}", user_followings_path(@user.id) %></th>
      </tr>
      <tr>
        <th>follower</th>
        <th><%= link_to "#{@user.followers.count}", user_followers_path(@user.id) %></th>
      </tr>
    </table>
    
    
    <div class='row'>
        <%= link_to edit_user_path(@user.id) ,class:"btn btn-outline-secondary btn-block fas fa-user-cog" do %>
        <% end %>
    </div>  



    <h2 class="mt-3">New book</h2>
    <%= form_with model:@book, local:true do |f| %>
      <div class="form-group">
        <label for="book_name">Title</label>
        <%= f.text_field :title, autofocus: true, class:"form-control",id:"inputTitle"%>
      </div>
      
    
      <div class="form-group">
        <label for="book_body">Opinion</label>
        <%= f.text_area :body, autofocus: true, class:"form-control",id:"inputBody"%>
      </div>
      
      
    <div class="action">
      <%= f.submit 'Create Book',class:"btn btn-success"%>
    </div>
    <% end %>
    
      
  </div>
     
 
 
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>  
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: "40x40"%>
              <% end %>    
            </td>
            <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
            <td><%= book.body %></td>
            <td id = "favorites-<%= book.id %>"><%= render 'favorites/favorites_btn', book: book  %></td>
            <td><%= "コメント数:#{book.book_comments.count}"%></td>
          </tr>  
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>










  
  





 

app/views/books/show.html.erb
<div class="container"> 
  <div class="row">  

    <%= render 'books/list', book: @book_list,user: @user_list  %>
 
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class='table'>
          <tr>
            <td>
              <%= link_to user_path(@book.user.id) do %>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg",size: "40x40" %>
              <br>
              <%= @book.user.name %>
              <% end %>
            </td>
            <td><%= link_to book_path(@book.id) do %><%= @book.title %><% end %></td>
            <td><%= @book.body %></td>
 
            <td id = "favorites-<%= @book.id %>"><%= render 'favorites/favorites_btn', book: @book  %></td>

 
            <td><% if @book.user == current_user %>
                 <%= link_to "Edit", edit_book_path(@book.id) ,class:'btn btn-sm btn-success edit_book_13499' %>
                <% end %>
            </td>
            
            <td><% if @book.user == current_user %>
                <%= link_to "Destroy", book_path(@book),class:'btn btn-sm btn-danger destroy_book_13499', method: :delete,"data-confirm" => "本当に消しますか？" %>
                <% end %>
          　</td>
          </tr>
      </table>
      
      <div id="comments">
          <%= render 'book_comments/comments', book: @book %>
      </div>
      
      <div class="new-comment">
        <%= render 'book_comments/new_comment', book: @book,book_comment: @book_comment %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_favorites_btn.html.erb
<% if book.favorited_by?(current_user)%>
  <p>
    <%= link_to book_favorites_path(book),method: :delete, remote: true do %>
    <i class="fas fa-heart like-btn" ><%= book.favorites.count %></i>
    <% end %>
  </p>
<% else %>
  <p>
    <%= link_to book_favorites_path(book),method: :post, remote: true do %>
    <i class="fas fa-heart unlike-btn"><%= book.favorites.count %></i>
    <% end %>
  </p>
<% end %> 

app/views/favorites/create.js.erb
$('#favorites-<%= @book.id %>').html('<%= j(render 'favorites/favorites_btn', book: @book ) %>');

app/views/favorites/destroy.js.erb
$('#favorites-<%= @book.id %>').html('<%= j(render 'favorites/favorites_btn', book: @book ) %>')

app/views/users/edit.html.erb
<div class='container'>

  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>User info</h2>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      
      <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <label for="user_name">Name</label>
        <%= f.text_field :name, autofocus: true, class:"form-control",id:"inputName"%>
      </div>
 
      <div class="form-group">
        <label for="user_image">Image</label>
        <%= f.attachment_field :profile_image, class: "w-100" %>
      </div>
      
      <div class="form-group">
        <label for="title">Introduction</label>
        <%= f.text_area :introduction, autofocus: true, class:"form-control",id:"inputintroduction"%>
      </div>
      <%= f.submit "Update User",class:"btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0"> 
  <div class="row">  

    <%= render 'books/list', book: @book_list,user: @user_list%>
    
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
    
      <table class='table'>
        <thead>
          <tr>
            <th>image</th> 
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: "40x40" %>
            <td><%= user.name %></td>
            <td>フォロー数: <%= user.followings.count %></td>
            <td>フォロワー数: <%= user.followers.count %></td>
            <td>
            <% if current_user != user %>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
              <% end %>
            <% end %>
            </td>
            <td><%= link_to 'Show', user_path(user.id) %></td>
          </tr>
          <% end %>
          
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0"> 
  <div class="row">  

    <%= render 'books/list', book: @book_list,user: @user %>
    
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: "40x40" %>
                  <% end %>
              </td>
              <td> <%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
              <td><%= book.body %></td>
              <td id = "favorites-<%= book.id %>"><%= render 'favorites/favorites_btn', book: book  %></td>
              <td><%= "コメント数:#{book.book_comments.count}" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>