config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  
  root to:'homes#top'
  get 'home/about' => 'homes#about'
  

  resources :books, only: [ :create, :edit, :update, :index, :show, :destroy] do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments,only: [:create,:destroy]
  end
  
  resources :users,only:[:index,:show,:edit,:update] do
    resource :relationships,only: [:create,:destroy]
    get 'followings' => 'relationships#followings', as:'followings'
    get 'followers' => 'relationships#followers', as:'followers'
  end
  
  get 'search' => "searches#search"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord


belongs_to :user
has_many :favorites,dependent: :destroy
has_many :book_comments,dependent: :destroy

def favorited_by?(user)
  favorites.where(user_id:user.id).exists?
end


  def self.looks(searches, words)
    if searches == "perfect_match"
      @book = Book.where("title LIKE ?","#{words}")
    elsif searches == "forward_match"
      @book = Book.where("title Like ?","#{words}%")
    elsif searches == "backward_match"
      @book = Book.where("title Like ?","%#{words}")
    else
      @book = Book.where("title LIKE ?","%#{words}%")
    end
  end

validates :title, presence: true
validates :body, presence: true, length: { maximum: 200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
belongs_to :user
belongs_to :book

validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

belongs_to :user
belongs_to :book

validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books,dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :book_comments,dependent: :destroy
  
  
  
  has_many :relationships, class_name: "Relationship",foreign_key: "follower_id",dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship",foreign_key: "followed_id",dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?","#{words}")
    elsif searches == "forward_match"
      @user = User.where("name Like ?","#{words}%")
    elsif searches == "backward_match"
      @user = User.where("name Like ?","%#{words}")
    else
      @user = User.where("name LIKE ?","%#{words}%")
    end
  end

  
  attachment :profile_image
  
validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
validates :introduction, length: { maximum: 50 }
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end
  
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if  @book.save
      flash[:notice] = 'Book was successfully created.'      
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user= current_user
      render :index
    end
  end
  
  
  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.' 
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  

  def show
    @book = Book.find(params[:id])
    @book_list = Book.new
    @user_list = @book.user
    @book_comment = BookComment.new
  end
  
  
  

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

def top
end

def about
end


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search],params[:word])
    else
      @books = Book.looks(params[:search],params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @book_list = Book.new
    @users = User.all
    @user_list = current_user
  end 
  
  
  
  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book_list = Book.new
  end
  
  
  def edit
   @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  

  
  
  private
  
  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notification.html.erb
<div class="Notification">
 <% flash.each do |key, value| %>
 <%= content_tag :div, value, class: key %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/aad5ca8bff.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark"> 
        <div class="container"> 
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <% if user_signed_in? %>
              <ul class="navbar-nav ml-auto">
                <li><%= link_to ' Home', user_path(current_user.id),class:'fas fa-home nav-link text-light' %></li>
                <li><%= link_to ' Users', users_path,class:'fas fa-users nav-link text-light'%></li>
                <li><%= link_to ' Books', books_path,class:'fas fa-book-open nav-link text-light'%></li>
                <li><%= link_to " logout", destroy_user_session_path,class:'fas fa-sign-out-alt nav-link text-light', method: :delete %></li>
              </ul>
            <% else %>
              <ul class="navbar-nav ml-auto">
                <li><%= link_to " Home", "/",class:'fas fa-home nav-link text-light' %></li>
                <li><%= link_to " About", home_about_path,class:'fas fa-link nav-link text-light' %></li>
                <li><%= link_to " sign up", new_user_registration_path,class:'fas fa-user-plus nav-link text-light'%></li>
                <li><%= link_to " login", new_user_session_path,class:'fas fa-sign-in-alt nav-link text-light' %></li>
              </ul>
            <% end %>
          </div>
        </div>
      </nav>
      <% if user_signed_in? %>
      <div class="search">
        <%= form_with url: search_path,method: :get,local: true do |f| %>
          <%= f.select :range, options_for_select([["User"],["Book"]]) %>
          <%= f.select :search, options_for_select([["完全一致","perfect_match"],["部分一致","partial_match"],["前方一致","forward_match"], ["後方一致","backward_match"]]) %>
          <%= f.text_field :word %>
          <%= f.submit :"検索" %>
        <% end %>
      <% end %>
      </div>

    </header> 
  
  <p id="notice"><%= notice %></p>
    
    <%= yield %>
    
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

    
    
  </body>
</html>